etl/dfta_contracts.py
sql/dfta_contracts.sql

Dfta_contracts

---

README.md
sql/doe_busroutesgarages.sql
sql/dohmh_daycare.sql

adding sql script to doe_busroutes, dohmh_daycare

---

etl/dsny_mtsgaragemaintenance.py
sql/dsny_mtsgaragemaintenance.sql

upload dsny_mtsgaragemaintenance.py and sql

upload dsny_mtsgaragemaintenance.py and sql

---

etl/bpl_libraries.py
etl/dca_operatingbusinesses.py
etl/dcas_colp.py
etl/dcla_culturalinstitutions.py
etl/dfta_contracts.py
etl/doe_busroutesgarages.py
etl/doitt_libraries.py
etl/dpr_parksproperties.py
etl/nycha_policeservice.py
etl/nysdoh_healthfacilities.py
etl/nysomh_mentalhealth.py
etl/nysopwdd_providers.py
etl/sbs_workforce1.py
etl/usnps_parks.py
etl/utils.py
sql/dca_operatingbusinesses.sql
sql/nysdoh_healthfacilities.sql
sql/nysopwdd_providers.sql
sql/usnps_parks.sql

Improved the code eligibility for
usnps_parks
dca_operatingbusinesses
dpr_parksproperties
nysdoh_healthfacilities
nysomh_mentalhealth
nysopwdd_providers
utils.py
Moved source geom adding processes from python to sql scripts

improve code eligibility

---

sql/bpl_libraries.sql
sql/dsny_mtsgaragemaintenance.sql
sql/nysdec_solidwaste.sql
sql/nysdoh_healthfacilities.sql

- Updated sql scripts for nysdec_solidwaste, nysdoh_healthfacilities and dsny_mtsgaragemaintenance, cause some data values have changed
- Updated wkt_geometry field for dsny_mtsgaragemaintenance, bpl_libraries at sql

48-enhancement

---

etl/usdot_airports.py
etl/usnps_parks.py
sql/qpl_libraries.sql
sql/usdot_airports.sql

- Added usdot_airports py and sql
- Reformatted usnps_parks py
- Commented out the first 3 rows in qpl_libraries.sql

add usdot_airports, update usnps_parks

---

etl/doe_lcgms.py
etl/nysed_activeinstitutions.py
etl/utils.py
lib/dump/postgis_dumper.py
sql/doe_lcgms.sql
sql/nysed_activeinstitutions.sql
sql/qpl_libraries.sql

- adding .sql
- adding .py 
note that nysed_nonpublicenrollment data is a supplymentry dataset to nysed_activeinstitutions
please run `nonpublicenrollment` first before `activeinstitutions`

3 nysed activeinstitutions

---

etl/usdot_ports.py
etl/utils.py
sql/usdot_ports.sql

add usdot_ports

---

etl/dcp_pops.py
etl/usdot_ports.py
etl/utils.py
sql/dcp_pops.sql
sql/usdot_ports.sql

question: 
Overagency: DCP or DOB?
@AmandaDoyle

5 dcp pops

---

etl/dcp_pops.py
etl/nypl_libraries.py
etl/usdot_ports.py
etl/utils.py
sql/dcp_pops.sql
sql/nypl_libraries.sql
sql/usdot_ports.sql

please review/confirm the following:

58 nypl libraries

---

etl/dot_mannedfacilities.py
etl/utils.py
sql/dot_mannedfacilities.sql

- add py and sql for dot_mannedfacilities
- update quick_clean() in utils.py

add dot_mannedfacilities.py and sql

---

etl/dcla_culturalinstitutions.py
etl/dfta_contracts.py
etl/doe_lcgms.py
etl/doitt_libraries.py
etl/foodbankny_foodbanks.py
etl/qpl_libraries.py
sql/dca_operatingbusinesses.sql
sql/dcla_culturalinstitutions.sql
sql/dcp_pops.sql
sql/doe_lcgms.sql
sql/doitt_libraries.sql
sql/foodbankny_foodbanks.sql
sql/nypl_libraries.sql
sql/nysdoh_healthfacilities.sql
sql/nysomh_mentalhealth.sql
sql/nysopwdd_providers.sql
sql/qpl_libraries.sql

- Tested cook recipes for all datasets except dcas_colp, doe_busroutesgarages, dohmh_daycare, which will take a while to run
- fixed the syntax errors regarding function ST_Point()
- removed the test printers in py and sql script
- Reviewed the sql script to ensure all column names have been referred in the right format (lowercase with underscores in between)

Fixed syntax errors regarding cook recipes

---

etl/dot_pedplazas.py
sql/dot_pedplazas.sql

- dataset only provides cross streets 
- these plazas are on the street bed

add dot_pedplazas.py and sql

---

etl/dep_wwtc.py
etl/fbop_corrections.py
sql/dcas_colp.sql
sql/dep_wwtc.sql
sql/fbop_corrections.sql
sql/load_and_combine.sql

```
facsubgrp = 'Justice and Corrections', 
```
or 
```
facsubgrp = 'Detention and Correctional',
```
?

84 fbop corrections

---

etl/dep_wwtc.py
sql/dcas_colp.sql
sql/dep_wwtc.sql
sql/load_and_combine.sql

- dep_wwtp
- dcas_colp --> needs further implementation
update: 
- fixed dcas_colp filtering

adding dep_wwtp, needs further implementation on optype

---

sql/nycha_communitycenters.sql

I think I fixed the error that produced all of the NULL values.

Fixed sql error

---

etl/doe_lcgms.py
sql/doe_lcgms.sql

"Hey!
@SPTKL already created a pipeline for the lcgms data so this pull request is just an update to that work.  I included capacity by joining on `((doe_lcgms.location_code || doe_lcgms.building_code) = (doe_bluebook.org_id || doe_bluebook.bldg_id))`.   
There are 1427 entries in Blue Book that are not included in the final merged dataset. I feel fine about this given that LCGMS is our main dataset and there are very few schools in LCGMS that do not have a BB match that can not be explained by the pre-K and charter school sanity checks from @mshapiro1.
My complete analysis of the dataset can be found here: https://github.com/NYCPlanning/db-facilities-tmp/blob/notebooks/notebooks/doe_bluebook.ipynb

104 doe bluebook

---

sql/assign_overlevel.sql
sql/dcas_colp.sql

Editing agency acronyms in COLP and adding script to assign oversight level

Classification

---

sql/dcp_pops.sql

Updating the hash value to be the pops_number for records from dcp_pops so that FacDB is compatible with the POPs explorer

changing the hash to be the pops_number

---

sql/dca_operatingbusinesses.sql
sql/dcp_pops.sql
sql/dycd_afterschoolprograms.sql
sql/moeo_socialservicesiteloactions.sql
sql/nycha_communitycenters.sql
sql/nypl_libraries.sql
sql/nysdoh_healthfacilities.sql
sql/qpl_libraries.sql

- Update sql queries involved 'None'
- Update `facname` mapping for moeo_socialservicesiteloactions

Update sql involved None and moeo_socialservicesiteloactions

---

sql/dcas_colp.sql
sql/nycourts_courts.sql

- Add courthouses from `dcas_colp`, remove the records if it exists in `nycourts_courts`
- Drop Summons Courts if there are duplicates in `nycourts_courts`

Add courthouses and deduplicate

---

facdb_build/facdb/recipes/nysed_activeinstitutions.py
facdb_build/sql/nysed_activeinstitutions.sql

Removes nysed_nonpublicinstitutions from geocoding script
Removes table join with nysed_activeinstitutions
Replaces updates with select

Remove nysed_nonpublic from nysed_activeinstitutions

---

facdb_build/facdb/recipes/nysed_activeinstitutions.py
facdb_build/sql/nysed_activeinstitutions.sql

Reverts NYCPlanning/db-facilities#306

Revert "Remove nysed_nonpublic from nysed_activeinstitutions"

---

.github/ISSUE_TEMPLATE/update.md

Include information we need about where to check if data needs to be updated, and what to check for.
I am still missing some info.

WIP: Improve issue temp

---

.github/workflows/main.yml

Switch to self-hosted runner

---

facdb_build/sql/dpr_parksproperties.sql

dpr_parksproperties - rename field to fix dpr_parksproperties.sql

---

facdb_build/sql/dcp_colp.sql

dcp_colp - Fix ownership flag and parcel name

---

facdb_build/facdb/recipes/dot_ferryterminals.py
facdb_build/sql/dot_ferryterminals.sql

dot_ferryterminals - name -> site

---

facdb_build/facdb/recipes/nysed_activeinstitutions.py
facdb_build/sql/nysed_activeinstitutions.sql

nysed_activeinstitutions - update field names and resolve errors

---

facdb_build/facdb/recipes/dot_publicparking.py
facdb_build/sql/dot_publicparking.sql

dot_publicparking - rename facaddress to address

---

facdb_build/sql/doe_lcgms.sql

we no longer take lat lon from source data

doe_lcgms - remove lat lon

---

facdb_build/facdb/recipes/dot_pedplazas.py
facdb_build/sql/dot_pedplazas.sql

dot_pedplazas - updating schema mapping

---

.github/workflows/main.yml

Add clean-up step

---

facdb_build/sql/dsny_mtsgaragemaintenance.sql

Change string NULLs to NULL for bbl field

---

facdb_build/facdb/recipes/dot_publicparking.py

Add facname and borocode

---

facdb_build/sql/dot_pedplazas.sql

Convert geom to point by finding centroid

---

facdb_build/sql/dohmh_daycare.sql

Delete acs_daycareheadstart dedup step

---

facdb_build/sql/dcp_colp.sql

Adds in 5 missing police precincts

339 dcp colp

---

facdb_build/facdb/recipes/dcp_colp.py

To fix https://github.com/NYCPlanning/db-facilities/runs/1577023553?check_suite_focus=true#step:4:118

Get geometry from wkb_geometry as text

---

facdb_build/sql/assign_geo_boundaries.sql

Addresses #353
Changes padding for school districts to 2 LPAD and police precincts to 3 LPAD

Fixing padding on school dist and police prect

---

facdb/datasets.yml
facdb/pipelines.py

Other group 1 extractors are complete

Add dca_culturalinstitutions, dcp_sfpsd, dcp_pops

---

facdb/geocode/functionBN.py

Fix BN typo

---

facdb/datasets.yml
facdb/pipelines.py
facdb/utility/export.py

Known issue: The usdot datasets are also displaying the problem of not getting `source` assigned when a filtered df is passed to export without geocoding

WIP: Add group 9 python

---

facdb/datasets.yml
facdb/pipelines.py

Add python extractors for new sources

---

README.md
facdb/cli.py
facdb/datasets.yml

see the new README for instructions

simplifying cli and updating documentation

---

facdb/datasets.yml
facdb/pipelines.py

Added nysomh_mentalhealth pipeline function

---

facdb/datasets.yml
facdb/pipelines.py
facdb/sql/nysoasas_programs.sql

I am having trouble with nysoasas_programs. When I load it on my local db it generates a random csv showing like it returned a 404. I used data library first and by mistake I used 04-Apr-2021 as the version which was not valid. Then I reran using the right version format 04-Apr-21. However, I still get that random table. I tested the other 3 and are working properly

Group 8 Python

---

.github/workflows/main.yml
facdb/cli.py
facdb/sql/_create_facdb_geom.sql
facdb/sql/dcp_colp.sql

Refactor geometry assignment

---

facdb/datasets.yml
facdb/pipelines.py
facdb/sql/foodbankny_foodbanks.sql
facdb/sql/hhc_hospitals.sql
facdb/sql/hra_jobcenters.sql
facdb/sql/hra_medicaid.sql
facdb/sql/hra_snapcenters.sql
facdb/sql/moeo_socialservicesitelocations.sql
facdb/sql/nycdoc_corrections.sql

Logic for MOEO data is not consistent with [old code](https://github.com/NYCPlanning/db-facilities/blob/main/facdb_build/sql/moeo_socialservicesiteloactions.sql) because we no longer have a factype from source data.
See available fields in issue #349

Group 5 SQL

---

facdb/sql/_create_facdb.sql

Switch from commboard to cd

---

facdb/sql/_create_facdb.sql

Add remove workflow

---

.devcontainer/Dockerfile
.github/workflows/main.yml
Dockerfile
facdb/bash/config.sh
facdb/bash/dataloading.sh
facdb/bash/export.sh
facdb/cli.py
facdb/sql/_create_facdb.sql
facdb/sql/_create_facdb_spatial.sql
facdb/sql/_qaqc.sql

#414 
- legacy qaqc checks are included

Adding qaqc tests

---

facdb/sql/nycha_communitycenters.sql

Add facsubgrp to nycha_communitycenters

---

facdb/sql/moeo_socialservicesitelocations.sql

#401
This currently has no ELSE statement. What should be the default facsubgrp?

Add MOEO facsubgrp classification

---

facdb/sql/nysdoh_nursinghomes.sql

This is why we're missing bed counts

Add missing capacity

---

facdb/sql/nysdoh_healthfacilities.sql

#453 
We only include records `WHERE description NOT LIKE '%Residential%'`

Filter out home care and remove residential facsubgrp

---

.github/workflows/main.yml
Dockerfile
facdb.sh
facdb/bash/config.sh
facdb/bash/export.sh
facdb/cli.py

#445 Will request review and merge after a successful run
Ready to go!

Adding FGDB export

---

facdb/data/lookup_agency.csv
facdb/sql/dcp_colp.sql

Change NYCCNTYC to CNTYC

---

facdb/sql/doe_lcgms.sql

excluding two facility types

---

facdb/cli.py
facdb/sql/_create_facdb.sql
facdb/sql/_create_facdb_spatial.sql
facdb/sql/_deduplication.sql

nycha community center deduplication

---

facdb/sql/_deduplication.sql

Cast bin as text before coalesce

---

facdb/pipelines.py

Add covid freeze date filter

---

facdb/sql/_deduplication.sql

Add Day Care and Youth center deduplication, also saving duplicates in facdb_duplicates

---

facdb/bash/export.sh
facdb/sql/_qaqc.sql

#465 -> QC on record counts, source counts vs final counts in facdb by datasource
#464 -> QC on bins by subgroup

Additional QAQC

---

Dockerfile
facdb/datasets.yml

update dcp_colp to use the latest release and bumping geosupport to 21b

---

facdb/sql/_qaqc.sql

updating logic so NULLs are not counted as duplicates

---

facdb/sql/_create_facdb_address.sql

Rewrite facdb_address

---

facdb/bash/config.sh

FGDB - needs to be projected to state plane

---

facdb/pipelines.py

Clean special characters from firehouse address

---

facdb/sql/_create_facdb.sql
facdb/sql/_create_facdb_address.sql

Remove leading/extra spaces
